const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const billingSchema = new Schema({
    // User this billing record belongs to
    user: {
        type: Schema.Types.ObjectId,
        ref: "User",
        required: true
    },
    
    // Billing period
    period: {
        type: String,
        required: true,
        enum: ['monthly', 'quarterly', 'yearly', 'custom'],
        default: 'monthly'
    },
    periodStart: {
        type: Date,
        required: true
    },
    periodEnd: {
        type: Date,
        required: true
    },
    
    // Financial summaries
    summary: {
        // As Guest (payments made)
        paymentsMade: {
            total: {
                type: Number,
                default: 0
            },
            count: {
                type: Number,
                default: 0
            },
            byStatus: {
                completed: { type: Number, default: 0 },
                pending: { type: Number, default: 0 },
                failed: { type: Number, default: 0 },
                refunded: { type: Number, default: 0 }
            }
        },
        
        // As Host (earnings received)
        earnings: {
            total: {
                type: Number,
                default: 0
            },
            count: {
                type: Number,
                default: 0
            },
            byStatus: {
                processed: { type: Number, default: 0 },
                pending: { type: Number, default: 0 },
                failed: { type: Number, default: 0 }
            },
            commission: {
                total: { type: Number, default: 0 },
                rate: { type: Number, default: 0.15 } // 15% platform fee
            }
        },
        
        // Refunds
        refunds: {
            received: {
                total: { type: Number, default: 0 },
                count: { type: Number, default: 0 }
            },
            issued: {
                total: { type: Number, default: 0 },
                count: { type: Number, default: 0 }
            }
        },
        
        // Outstanding amounts
        outstanding: {
            payments: { type: Number, default: 0 },
            payouts: { type: Number, default: 0 }
        }
    },
    
    // Tax information
    taxInfo: {
        taxableIncome: { type: Number, default: 0 },
        taxWithheld: { type: Number, default: 0 },
        taxDocumentsGenerated: { type: Boolean, default: false },
        taxDocumentUrl: String,
        vatNumber: String,
        taxId: String
    },
    
    // Currency and exchange rates
    currency: {
        type: String,
        default: 'USD',
        enum: ['USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'INR']
    },
    exchangeRates: {
        baseCurrency: { type: String, default: 'USD' },
        rates: {
            USD: { type: Number, default: 1 },
            EUR: Number,
            GBP: Number,
            JPY: Number,
            AUD: Number,
            CAD: Number,
            CHF: Number,
            CNY: Number,
            INR: Number
        }
    },
    
    // Related transactions
    transactions: [{
        type: Schema.Types.ObjectId,
        ref: "Transaction"
    }],
    
    // Document generation
    documents: {
        invoice: {
            generated: { type: Boolean, default: false },
            url: String,
            generatedAt: Date,
            documentId: String
        },
        receipt: {
            generated: { type: Boolean, default: false },
            url: String,
            generatedAt: Date,
            documentId: String
        },
        taxDocument: {
            generated: { type: Boolean, default: false },
            url: String,
            generatedAt: Date,
            documentId: String,
            type: { type: String, enum: ['w9', '1099', 'invoice', 'statement'] }
        }
    },
    
    // Status and processing
    status: {
        type: String,
        enum: ['draft', 'generated', 'sent', 'paid', 'overdue', 'cancelled'],
        default: 'draft'
    },
    
    // Metadata
    metadata: {
        autoGenerated: { type: Boolean, default: true },
        generatedBy: {
            type: Schema.Types.ObjectId,
            ref: "User"
        },
        lastCalculated: Date,
        version: { type: Number, default: 1 }
    },
    
    // Timestamps
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

// Indexes for performance
billingSchema.index({ user: 1, periodStart: -1 });
billingSchema.index({ user: 1, periodEnd: -1 });
billingSchema.index({ status: 1 });
billingSchema.index({ 'documents.invoice.generated': 1 });

// Update the updatedAt timestamp before saving
billingSchema.pre('save', function(next) {
    this.updatedAt = Date.now();
    next();
});

// Static method to generate billing summary for a user
billingSchema.statics.generateSummary = async function(userId, periodStart, periodEnd) {
    const Transaction = require('./transaction');
    
    // Get transactions for the period
    const transactions = await Transaction.find({
        $or: [
            { payer: userId },
            { payee: userId }
        ],
        createdAt: {
            $gte: periodStart,
            $lte: periodEnd
        }
    }).populate('booking');
    
    // Calculate summaries
    let paymentsMade = { total: 0, count: 0, byStatus: { completed: 0, pending: 0, failed: 0, refunded: 0 } };
    let earnings = { total: 0, count: 0, byStatus: { processed: 0, pending: 0, failed: 0 }, commission: { total: 0, rate: 0.15 } };
    let refunds = { received: { total: 0, count: 0 }, issued: { total: 0, count: 0 } };
    let outstanding = { payments: 0, payouts: 0 };
    
    transactions.forEach(transaction => {
        if (transaction.payer.equals(userId)) {
            // Payments made (as guest)
            paymentsMade.total += transaction.amount;
            paymentsMade.count++;
            paymentsMade.byStatus[transaction.status] = (paymentsMade.byStatus[transaction.status] || 0) + 1;
            
            if (transaction.status === 'pending') {
                outstanding.payments += transaction.amount;
            }
            
            if (transaction.type === 'refund') {
                refunds.received.total += transaction.refund?.refundAmount || transaction.amount;
                refunds.received.count++;
            }
        } else if (transaction.payee.equals(userId)) {
            // Earnings (as host)
            const hostEarnings = transaction.amount - (transaction.commission?.amount || 0);
            earnings.total += hostEarnings;
            earnings.count++;
            earnings.byStatus[transaction.status === 'completed' ? 'processed' : transaction.status]++;
            earnings.commission.total += transaction.commission?.amount || 0;
            
            if (transaction.status === 'pending') {
                outstanding.payouts += hostEarnings;
            }
            
            if (transaction.type === 'refund') {
                refunds.issued.total += transaction.refund?.refundAmount || transaction.amount;
                refunds.issued.count++;
            }
        }
    });
    
    return {
        paymentsMade,
        earnings,
        refunds,
        outstanding
    };
};

// Method to generate billing period key
billingSchema.methods.getPeriodKey = function() {
    const year = this.periodStart.getFullYear();
    const month = String(this.periodStart.getMonth() + 1).padStart(2, '0');
    
    if (this.period === 'yearly') {
        return `year-${year}`;
    } else if (this.period === 'quarterly') {
        const quarter = Math.ceil((this.periodStart.getMonth() + 1) / 3);
        return `Q${quarter}-${year}`;
    } else {
        return `${year}-${month}`;
    }
};

const Billing = mongoose.model("Billing", billingSchema);

module.exports = Billing;